##
# Proyecto 1
#
# @file
# @version 0.1
OBJETIVE=main.tex
PDF_COMPILE=pdflatex --shell-escape

make:
	$(PDF_COMPILE) $(OBJETIVE) && $(PDF_COMPILE) $(OBJETIVE)

clean:
	rm -rf *.toc *.log *.pdf *.out *.aux *.gz .auctex-auto/ _minted-main/ _region_.tex *.out *.lol *.lof


# end
